---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: statefulset-get-klusterlet-role
rules:
  - apiGroups: ["operator.open-cluster-management.io"]
    resources:
    - klusterlets 
    verbs: ["get", "list", "watch"]