apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "400"
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: centos
  name: centos7-instana
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeMode: Filesystem
  source:
    http:
      url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2111.qcow2 