---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: amazon-cloudwatch-channel
  namespace: amazon-cloudwatch
spec:
  pathname: https://${GIT_BASEURL}/${GIT_ORG}/otp-gitops-apps.git
  type: GitHub