apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: amazon-cloudwatch-subscription
  namespace: amazon-cloudwatch 
  labels:
    app: amazon-cloudwatch
  annotations:
      apps.open-cluster-management.io/git-branch: ${GIT_GITOPS_BRANCH} 
      apps.open-cluster-management.io/git-path: cluster-services/amazon-cloudwatch/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: amazon-cloudwatch/amazon-cloudwatch-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: amazon-cloudwatch-placement