apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cert-manager-placement-1
  namespace: cert-manager 
  labels:
    app: cert-manager
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      # Replace value with Cluster you wish to provision too.
      name: managed-roks-1