apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: vault-kms-gcp
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
      - roles/cloudkms.cryptoKeyEncrypterDecrypter
  secretRef:
    name: kms-cloud-credentials
    namespace: vault