apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: vault-kms-aws
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - kms:Encrypt
      - kms:Decrypt
      - kms:DescribeKey
      effect: Allow
      resource: '*'
  secretRef:
    name: kms-cloud-credentials
    namespace: vault