apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: vault-subscription
  namespace: vault 
  labels:
    app: vault
  annotations:
      apps.open-cluster-management.io/git-branch: ${GIT_GITOPS_BRANCH} 
      apps.open-cluster-management.io/git-path: tenants/vault/helm/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: vault/vault-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: vault-placement-1