apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: bank-appid-secret
  namespace: bank-infra
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secretstore-vault
    kind: ClusterSecretStore
  target:
    name: bank-appid-secret
  data:
  - secretKey: APPID_SERVICE_URL
    remoteRef:
      key: new-example-bank/bank-appid-secret
      property: APPID_SERVICE_URL
  - secretKey: APPID_TENANTID
    remoteRef:
      key: new-example-bank/bank-appid-secret
      property: APPID_TENANTID