---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: user-service
  name: user-service-placement-1
  namespace: bank-infra
spec:
  clusterSelector:
    matchLabels:
      'cluster.open-cluster-management.io/clusterset': 'multicloud-cluster-set'
