apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mcm-providers-trigger
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: mcm-providers-trigger
      template:
        name: mcm-providers-trigger

