apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mcm-providers-trigger
spec:
  params:
    - name: source-repo
      value: $(body.repository.url)
    - name: commit
      value: $(body.head_commit.id)

