---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-prometheus-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-predeploy-job-role-1
rules:
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get", "list", "watch", "create", "patch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-predeploy-job-role-2
rules:
  - apiGroups: ["operator.open-cluster-management.io"]
    resources:
    - klusterlets 
    verbs: ["get", "list", "watch"]