---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-credentails
  namespace: amazon-cloudwatch
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: secretstore-vault
    kind: ClusterSecretStore
  target:
    name: aws-credentials
  data:
  - secretKey: foobar
    remoteRef:
      key: secret/cloudwatch/
      property: aws-credentials