apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap-prometheus.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - anyuid-rolebinding.yaml
  - job-cwagent-configmap.yaml
  - externalsecret.yaml

#use the following to update the image
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: amazon/cloudwatch-agent:1.247348.0b251302
    target:
      kind: Deployment
      name: cwagent-prometheus