apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    kubernetes.io/metadata.name: external-secrets
    name: external-secrets
  name: external-secrets
spec:
  finalizers:
  - kubernetes
