apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-simulator-deployment
  labels:
    app: mobile-simulator
spec:
  selector:
    matchLabels:
      app: mobile-simulator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mobile-simulator
    spec:
      containers:
        - image: quay.io/alexocc/mybankfrontend:latest
          imagePullPolicy: Always
          name: mobile-simulator
          envFrom:
            - secretRef:
                name: mobile-simulator-secrets
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080
