apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: external-secrets-placement-1
  namespace: external-secrets 
  labels:
    app: external-secrets
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      # Replace value with Cluster you wish to provision too.
      name: managed-roks-1 