apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "450"
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: instana-vm
      vm.kubevirt.io/template: centos7-server-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.14.0
    name: instana-vm
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: instana-vm
      spec:
        pvc:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 160Gi
          volumeMode: Block    
        source:
          pvc:
            name: centos7-instana
            namespace: openshift-virtualization-os-images
    running: true
    template:
      metadata:
        annotations:
#          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: centos7
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: instana-vm
#          kubevirt.io/size: small
      spec:
        domain:
          cpu:
            cores: 12
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: instana-vm
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: 32Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: instana-vm
          name: instana-vm
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              package_upgrade: true
              yum_repos:
                docker-ce-stable:
                  baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
                  enabled: true
                  gpgcheck: true
                  gpgkey: https://download.docker.com/linux/centos/gpg
                  name: Docker CE Stable - $basearch
                instana-product:
                  baseurl: https://self-hosted.instana.io/rpm/release/product/rpm/generic/x86_64/Packages
                  enabled: true
                  gpgcheck: true
                  gpgkey: https://self-hosted.instana.io/signing_key.gpg
              packages:
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - instana-console
              user: centos
              password: password
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}